name: RandomMOTD
version: ${plugin.version}
main: me.JonathanHoffmann.randommotd.RandomMOTD
api-version: 1.19
commands:
  motdlist:
    usage: /<command> <id> [name]
    permission: randommotd.admin
    permission-message: You do not have permission!
  motdadd:
    usage: /<command> <id | name>
    permission: randommotd.admin
    permission-message: You do not have permission!
  motddelete:
    usage: /<command>
    permission: randommotd.admin
    permission-message: You do not have permission!
permissions:
  randommotd.admin:
    default: op